### DISCUSSION TITLE
How to set the dataset to BTech?

### DISCUSSION THREAD

**Discussion by brm738** [open-edge-platform/anomalib#161] [Q&A] [answered]
How to set the dataset to BTech in code and test these algorithms against its BTech classes like 01, 02 etc?

**Comment by samet-akcay** [comment, marked as answer]
Hi @brm738, the data section in the `config.yaml` file would be as follows:
```yaml
dataset:
  name: btech #options: [mvtec, btech, folder]
  format: btech
  path: ./datasets/BTech
  category: '01'
  task: segmentation
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config: null
  create_validation_set: false
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```

For instance, if you set the above configurations in `anomalib/models/patchcore/config.yaml`, and run `python tools/train.py --model patchcore`, you could train BTech dataset.

I've noticed that it throws an error when saving the results into file. You could avoid the error by changing `anomalib.utils.callbacks.visualizer_callback.py` `L84` as 

```python
if "local" in module.hparams.project.log_images_to:
    visualizer.save(Path(module.hparams.project.path) / "images" / filename.parent.name / filename.with_suffix(".png").name)
```
I'll create a PR for a hotfix for this.
