### DISCUSSION TITLE
[Task]: EfficientAD: Bad results in custom dataset with 1024*1040

### DISCUSSION THREAD

**Discussion by jiamfeng** [open-edge-platform/anomalib#1613] [Q&A]
### What is the motivation for this task?

Try to get results in custom datasets with segmentation task

### Describe the solution you'd like

when I use the efficientAd in custom dataset with 1024*1040(h * w), the results is very bad, how can I optimizer ?

### Additional context
```
dataset:
  name: xinyuan
  format: folder
  path: ./datasets/TS/gemo
  normal_dir: train # name of the folder containing normal images.
  abnormal_dir: test # name of the folder containing abnorm
  normal_test_dir: null # name of the folder containing normal test images.
  mask: null
  task: segmentation
  extensions: ".bmp"
  train_batch_size: 1
  eval_batch_size: 1
  mask_dir: null
  num_workers: 8
  image_size: [1024, 1040] # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: none # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: none # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: efficient_ad
  teacher_out_channels: 384
  model_size: small # options: [small, medium]
  lr: 0.0001
  weight_decay: 0.00001
  padding: false
  pad_maps: true # relevant for "padding: false", see EfficientAd in lightning_model.py
  # generic params
  normalization_method: min_max # options: [null, min_max, cdf]
```
