### DISCUSSION TITLE
Custom Data Set : KeyError:'label'

### DISCUSSION THREAD

**Discussion by jasperZoinks** [open-edge-platform/anomalib#164] [Q&A]
Hello,
I'm trying to create a custom data set for your library.

However I'm having some trouble with this.

The error i got:
[keyError](https://user-images.githubusercontent.com/79266435/160155413-32504236-64c4-42ab-b9d1-563dd8a04061.JPG)

This is the config file I created:
[ownConfigFile_Padim.txt](https://github.com/openvinotoolkit/anomalib/files/8351964/ownConfigFile_Padim.txt)

I'm working in Google Colab.

Thanks!

**Comment by preste-viunt** [comment]
I have the same problem

**Reply by samet-akcay** [reply]
Hi @jasperZoinks, I see that you set `task` to `segmentation` but don't provide `mask` folder. You could do one of the two

```yaml
dataset:
  name: walNUT                                          
  format: folder                                        
  path: /content/drive/MyDrive/masterIIW/nutsDataSet/training 
  normal: normal # name of the folder containing normal images.
  abnormal: abnormal # name of the folder containing abnormal images.
->task: segmentation # classification or segmentation   
->mask: path/to/your/mask/annotation
  extensions: null
  split_ratio: 0.2  # ratio of the normal images that will be used to create a test split
  seed: 0
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```


```yaml
dataset:
  name: walNUT                                          
  format: folder                                        
  path: /content/drive/MyDrive/masterIIW/nutsDataSet/training 
  normal: normal # name of the folder containing normal images.
  abnormal: abnormal # name of the folder containing abnormal images.
->task: classification # classification or segmentation   
->mask: null #optional
  extensions: null
  split_ratio: 0.2  # ratio of the normal images that will be used to create a test split
  seed: 0
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```

It would be safer if we check this condition. We'll create a PR for this
