### DISCUSSION TITLE
Benchmark with custom dataset

### DISCUSSION THREAD

**Discussion by Quentin-Jadoul** [open-edge-platform/anomalib#1697] [Q&A]
Hello!

I'm trying to benchmark different models on my custom dataset. I'm currently in version 0.7.0. My dataset has the following structure:
Run3
-Component1
--Good
--Bad
-Component2
--Good
--Bad
-...

How can i customize my benchmark config and model config to work properly? This is what i have for the moment:

- Benchmark

```
seed: 42
compute_openvino: false
hardware:
  - cpu
writer:
  - tensorboard
grid_search:
  dataset:
    category:
      - CM7V-T1A
      - LC79D
    image_size: [224, 256]
  model_name:
    - padim
```
    

-    Model

```
dataset:
  name: AOI
  format: mvtec
  path: ./datasets/Run3
  category: CM7V-T1A
  # normal_dir: Good # name of the folder containing normal images.
  # abnormal_dir: Bad # name of the folder containing abnormal images.
  # normal_test_dir: null # name of the folder containing normal test images.
  task: classification # classification or segmentation
  mask: null #optional
  extensions: null # .ext or [.ext1, .ext2, ...]
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
```
