### DISCUSSION TITLE
How to Export to Torch and openvino model for EfficientAd?

### DISCUSSION THREAD

**Discussion by nguyenanhtuan1008** [open-edge-platform/anomalib#1744] [General]
In v1 (also main branch) when I try to export model to Torch or OpenVino but I can found the way to do it. 
I want export it and then use the inference_torch.py or inference_openvino.py for inference.

I used command line for training: anomalib train --config <path/to/config>. Now I want to export the custom model to TORCH and OpenVINO model, how can I do it?

This my command:
`anomalib train --config /workspaces/anomalib/efficient_ad.yaml --data /workspaces/anomalib/mvtec.yaml
`
mvtec.yaml:

```
class_path: anomalib.data.MVTec
init_args:
  root: /workspaces/anomalib/datasets/MVTec
  category: mvt_20240209
  image_size: [512, 512]
  center_crop: null
  normalization: imagenet
  train_batch_size: 4
  eval_batch_size: 2
  num_workers: 8
  task: SEGMENTATION
  transform_config_train: null
  transform_config_eval: null
  test_split_mode: FROM_DIR
  test_split_ratio: 0.2
  val_split_mode: SAME_AS_TEST
  val_split_ratio: 0.5
  seed: null
```

and efficient_ad.yaml:

```
model:
  class_path: anomalib.models.EfficientAd
  init_args:
    teacher_out_channels: 384
    model_size: M
    lr: 0.0001
    weight_decay: 1.0e-05
    padding: false
    pad_maps: true
    batch_size: 1

metrics:
  pixel:
    - AUROC

trainer:
  max_epochs: 1000
  max_steps: 70000
```
I already try https://github.com/openvinotoolkit/anomalib/discussions/1670#discussion-6127755 but seems not work:
```
optimization:
  export_mode: null # options: torch, onnx, openvino
```
