### DISCUSSION TITLE
Inference results on CPU and GPU are different

### DISCUSSION THREAD

**Discussion by nakayamarusu** [open-edge-platform/anomalib#1858] [Q&A]
# **Problem**
Using Padim to learn images of MVTec bottles. And after exporting it to a file that can be used in Openvino, I did the inference in Openvino. I can get the correct heatmap if I infer on the CPU, but it doesn't work on the GPU. The GPU uses Intel iRIS Xew, and we have confirmed that OpenVino is compatible.

# **detail**
## Train
The learning process was as follows.
`anomalib fit -c configs/model/padim.yaml --data configs/folder_bottle.yaml`

▼ padim.yaml
```
model:
  class_path: anomalib.models.Padim
  init_args:
    layers:
      - layer1
      - layer2
      - layer3
    #input_size: [256, 256]
    backbone: resnet18
    pre_trained: true
    n_features: null

metrics:
  pixel: AUROC
```

▼ folder_bottle_yaml
```
class_path: anomalib.data.Folder
init_args:
  name: bottle
  root: "dataset/bottle"
  normal_dir: "train/good"
  abnormal_dir: "test/broken_large"
  normal_test_dir: "test/good"
  mask_dir: "ground_truth/broken_large"
  normal_split_ratio: 0
  extensions: [".png"]
  image_size: [256, 256]
  #center_crop: null
  #normalization: imagenet
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  task: CLASSIFICATION
  #transform_config_train: null
  #transform_config_eval: null
  test_split_mode: NONE
  test_split_ratio: 0.2
  val_split_mode: same_as_test
  val_split_ratio: 0.5
  seed: null
```
## Export
The export was performed as follows.
`anomalib export --model Padim --export_type OPENVINO --ckpt_path results/Padim/bottle/latest/weights/lightning/model.ckpt`

## Inference
The inference was made by creating python code as follows.
```python
from anomalib.deploy.inferencers import OpenVINOInferencer
import cv2
import numpy as np
import os

inferencer = OpenVINOInferencer(
    path=r"C:\anomalib_v1\results\weights\openvino\model.onnx",
    metadata=r"C:\anomalib_v1\results\weights\openvino\metadata.json",
    device="GPU",
)

img_path = r"C:\anomalib_v1\dataset\bottle\test\broken_small"

for i, file in enumerate(os.listdir(img_path)):
    
    image = cv2.imread(img_path + "\\" + file)
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    input_img = image.astype(np.float32) / 255.0 
    result = inferencer.predict(image = input_img)
    print(i, result.pred_score)
    cv2.imshow("heatmap", cv2.cvtColor(result.heat_map, cv2.COLOR_RGB2BGR))
    cv2.waitKey()
```

# Inference result
Heat map when the device used for inference is CPU as shown below

```python
inferencer = OpenVINOInferencer(
    path=r"C:\anomalib_v1\results\weights\openvino\model.onnx",
    metadata=r"C:\anomalib_v1\results\weights\openvino\metadata.json",
    device="CPU",
)
```
![heatmap1](https://github.com/openvinotoolkit/anomalib/assets/163484775/85e720ff-924b-46ef-afe9-82b79bca0913)
▲ pred_score : 0.4836

![heatmap2](https://github.com/openvinotoolkit/anomalib/assets/163484775/4f5ba28b-cb75-4d65-b5e2-5c17080091b6)
▲ pred_score : 0.5605

Heat map when the device used for inference is GPU as shown below

```python
inferencer = OpenVINOInferencer(
    path=r"C:\anomalib_v1\results\weights\openvino\model.onnx",
    metadata=r"C:\anomalib_v1\results\weights\openvino\metadata.json",
    device="GPU",
)
```
![heatmap3](https://github.com/openvinotoolkit/anomalib/assets/163484775/abb0ace8-3cde-4f01-8a68-e3daf234fb3d)
▲ pred_score : 0.0

![heatmap4](https://github.com/openvinotoolkit/anomalib/assets/163484775/29b6c949-a7fc-4f6d-8b0a-5b368d7e8907)
▲ pred_score : 0.0

Both CPU and GPU inference use the same model.
Also, only the device = "CPU" and device = "GPU" parts have been changed.
I changed the OpenVino version from 2024.0.0 to 2023.2.0 and tried inference, but it doesn't work

# Question
If I just switch the device used from CPU to GPU, I cannot get correct inference results. How can we improve it to enable inference on GPU?
