### DISCUSSION TITLE
i have upgraded old config to new config .

### DISCUSSION THREAD

**Discussion by yvr354** [open-edge-platform/anomalib#1983] [General]
when i try to run padim model on my custom data.
![error](https://github.com/openvinotoolkit/anomalib/assets/68755664/afdf39fa-9032-43f1-82dd-87f6311cba83)
this is my padim config file 
```yaml
data:
  class_path: anomalib.data.Folder
  init_args:
    name: custom
    normal_dir: GOOD
    root: .R:\Bumpers\anomalib1.0\dataset
    abnormal_dir: REJECT
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 32
    eval_batch_size: 32
    num_workers: 8
    task: classification
    image_size:
    - 800
    - 800
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: from_test
    val_split_ratio: 0.5
    seed: 0
model:
  class_path: anomalib.models.Padim
  init_args:
    backbone: resnet18
    layers:
    - layer1
    - layer2
    - layer3
    pre_trained: true
    n_features: null
normalization:
  normalization_method: min_max
metrics:
  image:
  - F1Score
  - AUROC
  pixel:
  - F1Score
  - AUROC
  threshold:
    class_path: anomalib.metrics.F1AdaptiveThreshold
    init_args:
      default_value: 0.5
visualization:
  visualizers: null
  save: true
  log: true
  show: false
logging:
  log_graph: true
seed_everything: true
task: classification
results_dir:
  path: ./results
  unique: false
ckpt_path: null
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  overfit_batches: 0.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 5
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  deterministic: false
  benchmark: false
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
```
Can anyone help me to solve this isssue .
