### DISCUSSION TITLE
Tiling in config.yaml?

### DISCUSSION THREAD

**Discussion by ChrisEvo3** [open-edge-platform/anomalib#2000] [Q&A]
I would like to activate tililng in the config.yaml file. Where does the tiling block have to go?

I always get this error:
error: Validation failed: No action for key "tiling.apply" to check its value.

```
data:
  class_path: anomalib.data.Folder
  init_args:
    name: test1
    root: datasets/test1
    normal_dir: good # name of the folder containing normal images.
    abnormal_dir: abnormal # name of the folder containing abnormal images.
    normal_test_dir: null # name of the folder containing normal test images.
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 2
    eval_batch_size: 2
    num_workers: 8
    image_size: null
    transform: null
    train_transform: null
    eval_transform: null
    test_split_mode: FROM_DIR
    test_split_ratio: 0.2
    val_split_mode: FROM_TEST
    val_split_ratio: 0.5
    seed: null
tiling:
  apply: true
  tile_size: 100
  stride: 100
  remove_border_count: 0
  use_random_tiling: False
  random_tile_count: 16
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
    - layer2
    - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
```
