### DISCUSSION TITLE
How can I train a model tracking the image-level AUROC (classification)

### DISCUSSION THREAD

**Discussion by mjack3** [open-edge-platform/anomalib#2125] [Q&A]
Let's suppose the following code

`anomalib train --config configs/model/csflow.yaml  --data --configs/data/mvtec.yaml`

I have set in the model config file:

```
model:
  class_path: anomalib.models.Csflow
  init_args:
    cross_conv_hidden_channels: 1024
    n_coupling_blocks: 4
    clamp: 3
    num_channels: 3

metrics:
  image:
    - AUROC

trainer:
  max_epochs: 20
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 100
        monitor: image_AUROC
        mode: max

```

and the following in the data config file

`task: classification`

But the pixel auroc is always tracked during training. Am I missing something?
