### DISCUSSION TITLE
Anomalib 1.0 transformations

### DISCUSSION THREAD

**Discussion by oscarllarch** [open-edge-platform/anomalib#2220] [Q&A]
Hi,

Could someone post an example of using transofmrations on a custom dataset with new Anomalib version using CLI? 
I've tryied this:

```
transform:
        class_path: torchvision.transforms.v2.ColorJitter
        init_args:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.2
```
I get the error "ValueError: Fastflow needs input size to build torch model".

The config file also contains:
```
image_size:
    - 512
    - 512
```

The model I'm trying to train is Fastflow.

Thanks,

**Comment by samet-akcay** [comment]
Hi @oscarllarch, can you share your model config?

**Comment by oscarllarch** [comment]
```
data:
  class_path: anomalib.data.Folder
  init_args:
    name: sd
    normal_dir: train/ok
    root: ./images
    abnormal_dir: test/error
    normal_test_dir: null
    mask_dir: null
    normal_split_ratio: 0.2
    extensions: null
    train_batch_size: 6
    eval_batch_size: 6
    num_workers: 4
    task: classification
    image_size:
    - 512
    - 512
    
    transform:
        class_path: torchvision.transforms.v2.ColorJitter
        init_args:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.2

    #train_transform: null
    #eval_transform: null
    test_split_mode: from_dir
    test_split_ratio: 0.2
    val_split_mode: same_as_test
    val_split_ratio: 0.5
    seed: null
model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: resnet18
    pre_trained: true
    flow_steps: 8
    conv3x3_only: false
    hidden_ratio: 1.0
normalization:
  normalization_method: min_max
metrics:
  image:
  - F1Score
  - AUROC
  pixel:
  - F1Score
  - AUROC
logging:
  log_graph: false
seed_everything: true
task: classification
ckpt_path: null
trainer:
  accelerator: gpu
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: 100
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  overfit_batches: 0.0
  val_check_interval: 1.0
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: 50
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: true
  accumulate_grad_batches: 1
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  deterministic: false
  benchmark: false
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
  callbacks:
    - class_path: lightning.pytorch.callbacks.EarlyStopping
      init_args:
        patience: 8
        monitor: image_AUROC
        mode: max
```

**Comment by samet-akcay** [comment]
hmm, it might be because you are passing a custom transform, which overwrites the `image_size` argument. Can you remove `image_size` and add this to your custom transforms

```yaml
        - class_path: torchvision.transforms.v2.Resize
          init_args:
            size: [512, 512]
```

so your overall transforms would be like

```yaml
transform:
  - class_path: torchvision.transforms.v2.Resize
    init_args:
      size: [512, 512]
  - class_path: torchvision.transforms.v2.ColorJitter
    init_args:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.2
```

**Reply by oscarllarch** [reply]
Hi,

Output:
```
error: Parser key "data":
  Problem with given class_path 'anomalib.data.Folder':
    Parser key "transform":
      Does not validate against any of the Union subtypes
      Subtypes: (<class 'torchvision.transforms.v2._transform.Transform'>, <class 'NoneType'>)
      Errors:
        - Not a valid subclass of Transform
          Subclass types expect one of:
          - a class path (str)
          - a dict with class_path entry
          - a dict without class_path but with init_args entry (class path given previously)
        - Expected a <class 'NoneType'>
      Given value type: <class 'list'>
      Given value: [{'class_path': 'torchvision.transforms.v2.Resize', 'init_args': {'size': [512, 512]}}, {'class_path': 'torchvision.transforms.v2.ColorJitter', 'init_args': {'brightness': 0.2, 'contrast': 0.2, 'saturation': 0.2, 'hue': 0.2}}]
```

Removing the dash: "class_path: torchvision.transforms.v2.Resize" instead of "- class_path: torchvision.transforms.v2.Resize":
```
transform:
        class_path: torchvision.transforms.v2.Resize
        init_args:
            size: [512, 512]
      
        class_path: torchvision.transforms.v2.ColorJitter
        init_args:
            brightness: 0.2
            contrast: 0.2
            saturation: 0.2
            hue: 0.2
```
Same error: "ValueError: Fastflow needs input size to build torch model".

Thanks,
