### DISCUSSION TITLE
MLflow Logger not working correctly with AnomalibCLI

### DISCUSSION THREAD

**Discussion by Samyarrahimi** [open-edge-platform/anomalib#2259] [Q&A]
I have been using anomalibCLI to fit a model(FastFlow) on my dataset. I want to use AnomalibMLflowLogger to log the metrics and parameters. This is the configuration file that I pass to the fit command of anomalibCLI, but it only logs the meta.yaml file in a folder inside mlruns folder, and nothing else is logged. Am I passing a value incorrectly or missing something?

I was able to log the metrics with MLflow using the Python API, but for some reason, I can't do it with the CLI.

I'd be happy to provide more information if needed. Thanks in advance for your help.

This is how i run the CLI command:
```
import subprocess

if __name__ == "__main__":
    config_file_path = "configs/mbh.yaml"
    command = f"anomalib fit --config {config_file_path}"
    subprocess.run(command, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, universal_newlines=True)
```

mlflow logs:
![image](https://github.com/user-attachments/assets/4f9e11d1-c711-4196-9386-9f7d5e8e7ef8)

config file:

```
default_root_dir: results
data:
  class_path: anomalib.data.Folder
  init_args:
    abnormal_dir: train_and_val/abnormal
    eval_batch_size: 4
    eval_transform: null
    extensions:
    - .jpg
    image_size:
    - 224
    - 224
    mask_dir: None
    name: MBH
    normal_dir: train_and_val/normal
    normal_split_ratio: 0
    normal_test_dir: test/normal
    num_workers: 4
    root: #root_of_my_dataset
    seed: 42
    task: classification
    test_split_mode: from_dir
    test_split_ratio: 0.2
    train_batch_size: 4
    train_transform: null
    transform:
      class_path: torchvision.transforms.v2.Resize
      init_args:
        size: 224
    val_split_mode: from_train
    val_split_ratio: 0.2
metrics:
  image:
  - F1Score
  - AUROC
  pixel:
  - F1Score
  - AUROC
model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: resnet18
    conv3x3_only: false
    flow_steps: 8
    hidden_ratio: 1.0
    pre_trained: true
optimizer:
  class_path: torch.optim.AdamW
  init_args:
    amsgrad: false
    betas:
    - 0.9
    - 0.999
    capturable: false
    differentiable: false
    eps: 1.0e-08
    foreach: null
    fused: null
    lr: 0.003
    maximize: false
    weight_decay: 0.01
seed_everything: true
task: classification
trainer:
  accelerator: auto
  callbacks:
    class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      mode: max
      monitor: Image_F1Score
      patience: 5
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  gradient_clip_algorithm: norm
  inference_mode: true
  log_every_n_steps: 5
  logger:
    class_path: anomalib.loggers.AnomalibTensorBoardLogger
    init_args:
      save_dir: "tensorboard_logs"
    class_path: anomalib.loggers.AnomalibMLFlowLogger
    init_args:
      save_dir: ./mlruns
      experiment_name: anomalib_logs2
      log_model: all
      tags:
        dataset: partB
        model: Fastflow
  max_epochs: 9
  precision: 16-mixed
```
