### DISCUSSION TITLE
ValueError: optimizer got an empty parameter list

### DISCUSSION THREAD

**Discussion by Samyarrahimi** [open-edge-platform/anomalib#2296] [Q&A]
I’m encountering an issue while training the FastFlow model on my custom dataset. I’m receiving the following error:
`ValueError: optimizer got an empty parameter list`

I’m using the Engine.from_config(config_file_path) method to initialize the engine, model, and datamodule from a YAML configuration file. Here’s the code snippet where I initialize the engine:
`engine, model, datamodule = Engine.from_config(config_file_path)`

Here’s the YAML configuration file I’m using:
```
data:
  class_path: anomalib.data.Folder
  init_args:
    abnormal_dir: train_and_val/abnormal
    eval_batch_size: 8
    extensions:
    - .jpg
    image_size:
    - 256
    - 256
    name: #name
    normal_dir: train_and_val/normal
    normal_split_ratio: 0
    normal_test_dir: test/normal
    num_workers: 4
    root: #root-of-my-dataset
    seed: 42
    task: classification
    test_split_mode: from_dir
    test_split_ratio: 0.2
    train_batch_size: 8
    val_split_mode: same_as_test
metrics:
  image:
  - F1Score
  - AUROC
  pixel:
  - F1Score
  - AUROC
model:
  class_path: anomalib.models.Fastflow
  init_args:
    backbone: wide_resnet50_2
    conv3x3_only: false
    flow_steps: 8
    hidden_ratio: 1.0
    pre_trained: true

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 0.0004
    weight_decay: 1.0e-05

seed_everything: true
task: classification

trainer:
  accelerator: auto
  callbacks:
    class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      mode: max
      monitor: image_F1Score
      patience: 5
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  gradient_clip_algorithm: norm
  inference_mode: true
  log_every_n_steps: 5
  logger:
    class_path: anomalib.loggers.AnomalibMLFlowLogger
    init_args:
      experiment_name: Fastflow-exp
      log_model: true
      run_name: fastflow-run1
  max_epochs: 14
  precision: 16-mixed
```
