### DISCUSSION TITLE
How to convert Model from PyTorch -> ONNX -> TensorFlow -> TFLite  ? How to do Model compression/optimization ?

### DISCUSSION THREAD

**Discussion by Abhijeet241093** [open-edge-platform/anomalib#2459] [Q&A]
### Describe the bug

How to convert Model from PyTorch -> ONNX -> TensorFlow -> TFLite and compare theirs performance (speed and accuracy) ? for patchcore

Model compression/optimization: How to compare four models and provide theirs performance (speed and accuracy) ? patchcore

### Dataset

MVTec

### Model

PatchCore

### Steps to reproduce the behavior

Thank you 

### OS information

OS information:
- OS: [e.g. Ubuntu 20.04]
- Python version: [e.g. 3.10.0]
- Anomalib version: [e.g. 0.3.6]
- PyTorch version: [e.g. 1.9.0]
- CUDA/cuDNN version: [e.g. 11.1]
- GPU models and configuration: [e.g. 2x GeForce RTX 3090]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

How to convert Model from PyTorch -> ONNX -> TensorFlow -> TFLite and compare theirs performance (speed and accuracy) ? for patchcore

Model compression/optimization: How to compare four models and provide theirs performance (speed and accuracy) ? patchcore

### Pip/GitHub

GitHub

### Configuration YAML

```yaml
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
      - layer2
      - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
```

### Logs

```shell
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
      - layer2
      - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
