### DISCUSSION TITLE
Anomalib with CUDA

### DISCUSSION THREAD

**Discussion by glucasol** [open-edge-platform/anomalib#524] [Q&A] [answered]
Is it possible to run anomalib on CUDA? If so, how can I do this?

**Comment by djdameln** [comment, marked as answer]
By default, Anomalib installs a version of PyTorch that includes CUDA support, so if your system is equipped with a compatible GPU, it should automatically run on CUDA. If this is not the case, could you please provide us with more details about your system configuration, and the steps you took to install and run Anomalib?

**Reply by JACKYNIKK** [reply]
@djdameln  i'm also trying to run on cuda. I created a new enviroment. installed pytorch with the command "pip3 install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu113" as suggested. And at that point "torch.cuda.is_available()" says true. Then i immediately wrote pip install anomalib. And now the "torch.cuda.is_available()" say false. Why is this and how to solve it? if "torch.cuda.is_available()" becomes "true"again does anomalib then automaticcally recognize the gpu if i set the accelerator as gpu in the config files?

**Reply by JACKYNIKK** [reply]
The solution for me was the one suggested by @samet-akcay in issue #518. I needed to install Anomalib (pip install anomalib) and after that downgrade the torch version with the line of code proposed in the aforementioned issue:
pip install torch==1.11.0+cu113 torchvision==0.12.0+cu113 torchaudio==0.11.0 --extra-index-url https://download.pytorch.org/whl/cu113


Since for my case installing anomalib with pip install anomalib automatically installed a versione of torch (1.12.1) which was not recognizing the GPU it was needed to install the version of torchvision (and also torchvision and torchaudio) which recognized it. This , as said, was done with that command line above.

Hope this helps, thank you anyway for this great repo :)

**Reply by freedom-cui** [reply]
Hello, this week I found a strange problem when training own data with ```padim```, it doesn't seem to call the GPU to complete the training. ```My CUDA version is 11.3, my graphics card is a 2080Ti, and my python version is 3.8.``` I'm pretty sure I can use my CUDA properly, and confirmed that the GPU version of pytorch works fine. However, when I trained with padim, my Yaml used the same Yaml I sent before, but I only made one change to the previous version of YAML, which was to change ```"num_workers: 8" to "num_workers: 0"```. My program reports an error at "num_workers: 8". At "num_workers: 0" I am training correctly, ```but it seems to be training with the CPU```.

Please take a look at the following graph, it may have some Chinese information, but it does not affect the observation of CPU and GPU calls. How can I solve this problem?

As you can see from the graph, my CPU takes up a lot of memory during training, but the GPU utilization is 0%, which I think is due to the fact that I am not calling CUDA correctly. This is also the case when I change the "num_workers" to 1.

 I am looking forward to your answer, thank you very much!

![cpu_gpu](https://user-images.githubusercontent.com/81297486/232729030-9d5034ef-3d7f-4bf5-9e12-99f822730f53.png)

My GPU :RTX2080Ti
My CUDA : CUDA 11.3
python version: 3.8
Anomalib version：  0.5.0（latest）
！！！pytorch indicates that I can use CUDA normally  （torch.cuda.is_available = True）

My config.yaml:
```
dataset:
  name: mydata
  format: folder
  path: ./Mydatasets/cubes
  normal_dir: normal # 独有 name of the folder containing normal images.
  abnormal_dir: abnormal # 独有 name of the folder containing abnormal images.
  normal_test_dir: null # 独有 name of the folder containing normal test images.
  task: classification # classification or segmentation
  mask: null #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 256
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 4
  transform_config:
    train: null
    eval: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: from_dir # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.1 # fraction of train/test images held out for validation (usage depends on val_split_mode)

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 42
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: null #options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 30
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle


```
