### DISCUSSION TITLE
Grayscale Image Source

### DISCUSSION THREAD

**Discussion by rumanto00** [open-edge-platform/anomalib#665] [Q&A] [answered]
Is possible to use grayscale image on anomalib with RGB Resnet Transfer Learning?
and where the setting on anomalib for 1 channel image?

Thanks

**Comment by Jonas1302** [comment]
I haven't tested it but you could try to use a `transform_config` like they did with DRAEM (see its [config.yaml](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/draem/config.yaml#L12) and [transform_config.yaml](https://github.com/openvinotoolkit/anomalib/blob/main/anomalib/models/draem/transform_config.yaml)).
Adding [ToRGB](https://albumentations.ai/docs/api_reference/augmentations/transforms/#albumentations.augmentations.transforms.ToRGB) to the inner `transforms` list (right before `ToFloat`) may do it.

**Comment by samet-akcay** [comment, marked as answer]
@rumanto00, I agree with @Jonas1302. You could create your custom transforms and add it to your `config.yaml` file as @Jonas1302 suggested.

For example, here is a code snippet how you could generate those transform configs via albumentations.

```python
from skimage import data
import albumentations as A
from albumentations.pytorch import ToTensorV2

image = data.camera()

transforms = A.Compose([A.ToRGB(), ToTensorV2()])
transformed_image = transforms(image=image)["image"]

# (512, 512) torch.Size([3, 512, 512])
print(image.shape, transformed_image.shape)

A.save(transforms, "transforms.yaml", data_format="yaml")
```

This would save the transforms to `transforms.yaml` file, which would be something like the following:
```yaml
__version__: 1.3.0
transform:
  __class_fullname__: Compose
  additional_targets: {}
  bbox_params: null
  is_check_shapes: true
  keypoint_params: null
  p: 1.0
  transforms:
  - __class_fullname__: ToRGB
    always_apply: true
    p: 1.0
  - __class_fullname__: ToTensorV2
    always_apply: true
    p: 1.0
    transpose_mask: false
```

> **_NOTE:_**
`ToRGB` has just been added to `albumentations`. You will need to install albumentations package from source since this change is not on PyPI yet.
