### DISCUSSION TITLE
Config-Files have wrong structure?

### DISCUSSION THREAD

**Discussion by WAKCL** [open-edge-platform/anomalib#671] [Q&A] [answered]
**Describe the bug**

- It seems like the default config files are completley in the wrong structure. When i use e.g. configs/model/padim.yaml, i get an error for a missing key: "project". After adding project, it tells me its missing project.path. After fixing that, it tells me its missing metrics.threshold. After fixing that, it tells me its missing metrics.threshold.adaptive. And so on. 

**To Reproduce**

1. Just follow the installation guide
2. Edit *data* section inside padim.yaml with custom *dataset* like mentioned in the README!
3. Call `python tools/train.py --config configs/model/padim.yaml`

**Screenshots**
![image](https://user-images.githubusercontent.com/117358077/199709299-9a71c7b9-b6af-44b4-875b-ce7ca8e49214.png)

**Hardware and Software Configuration**

- OS: Windows 10
- CUDA Version 10.2
- CUDNN Version 7.5.6

**Comment by WAKCL** [comment]
Here are my installed dependencies and their versions: 
[installed_libs.txt](https://github.com/openvinotoolkit/anomalib/files/9927876/installed_libs.txt)

The used config file looks like this:
```
# This is the config file for the new Anomalib CLI.
# To use this, run the following command:
# anomalib fit --config ./config/model/padim.yaml
ckpt_path: null
seed_everything: null

dataset:
  name: NAME
  format: folder
  path: PATH-TO-PROJECT
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: bad # name of the folder containing abnormal images.
  normal_test_dir: null # name of the folder containing normal test images.
  task: segmentation # classification or segmentation
  mask: null #optional
  extensions: null
  split_ratio: 0.2 # ratio of the normal images that will be used to create a test split
  image_size: 512
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  transform_config:
    train: null
    val: null
  create_validation_set: true
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: padim
  class_path: anomalib.models.Padim
  init_args:
    input_size:
      - 512 # Height
      - 512 # Width
    backbone: resnet18
    pre_trained: true
    layers:
      - layer1
      - layer2
      - layer3

post_processing:
  normalization_method: min_max # <null, min_max, cdf>
  threshold_method: adaptive # options: [adaptive, manual]
  manual_image_threshold: null
  manual_pixel_threshold: null

metrics:
  image_metrics:
    - F1Score
    - AUROC
  pixel_metrics:
    - F1Score
    - AUROC

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: False # log images to the available loggers (if any)
  mode: full # options: ["full", "simple"]

trainer:
  logger: true
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 50
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  resume_from_checkpoint: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.
```
