### DISCUSSION TITLE
pixelwise metrics JaccardScore

### DISCUSSION THREAD

**Discussion by kusstox** [open-edge-platform/anomalib#864] [Q&A]
Hi everyone
I would like to calculate my pixelwise JaccardIndex (IoU score). Now I found in this question, that I can extend my metrics list with common torchmetrics:  [https://github.com/openvinotoolkit/anomalib/discussions/781](https://github.com/openvinotoolkit/anomalib/discussions/781)

So I did and it works with Dice for instance, but when I enter JaccardIndex I do not get any warning but also no output of the Jaccard Score. Why?

Config:
```
dataset:
  name: synthetic2
  format: folder
  path: ./datasets/SyntheticData
  normal_dir: good # name of the folder containing normal images.
  abnormal_dir: anomalous # name of the folder containing abnormal images.
  task: segmentation
  mask: ./mask
  normal_test_dir: null # optional
  extensions: null
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  image_size: 
  - 256
  - 256
   # dimensions to which images are resized (mandatory)
  center_crop: null # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: True
    tile_size: 256
    stride: null
    remove_border_count: 0
    use_random_tiling: True
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
  pixel:
    - F1Score
    - Precision
    - JaccardIndex
    - Dice

  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [csv] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: True # Logs the model graph to respective logger.

optimization:
  export_mode: null # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  accumulate_grad_batches: 1
  amp_backend: native
  auto_lr_find: false
  auto_scale_batch_size: false
  auto_select_gpus: false
  benchmark: false
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  default_root_dir: null
  detect_anomaly: false
  deterministic: false
  devices: 1
  enable_checkpointing: true
  enable_model_summary: true
  enable_progress_bar: true
  fast_dev_run: false
  gpus: null # Set automatically
  gradient_clip_val: 0
  ipus: null
  limit_predict_batches: 1.0
  limit_test_batches: 1.0
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  log_every_n_steps: 1
  log_gpu_memory: null
  max_epochs: 1
  max_steps: -1
  max_time: null
  min_epochs: null
  min_steps: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  num_nodes: 1
  num_processes: null
  num_sanity_val_steps: 0
  overfit_batches: 0.0
  plugins: null
  precision: 32
  profiler: null
  reload_dataloaders_every_n_epochs: 0
  replace_sampler_ddp: true
  strategy: null
  sync_batchnorm: false
  tpu_cores: null
  track_grad_norm: -1
  val_check_interval: 1.0 # Don't validate before extracting features.

```

Output:
![image](https://user-images.githubusercontent.com/82957504/214315326-c0063f07-63d0-4103-8729-be980de19ed6.png)

Where is my JaccardIndex?
