### DISCUSSION TITLE
Inference with TorchInferencer - Creating empty directories when instantiating a new inferencer

### DISCUSSION THREAD

**Discussion by tominator95** [open-edge-platform/anomalib#948] [Q&A]
Hi,
it's me again :-). When I instantiate a new ```TorchInferencer``` some (empty) directories are created and files are moved. I want to prevent this. I will explain it in more detail:
My code: 
```python
inferencer = TorchInferencer(config="<<path to config>>", model_source="<<path to weights file>>", device="auto")
```
Snippet of config.yaml (I removed some information):
```yaml
dataset:
  name: padim_test
  format: folder
  path: /opt/<<path to images>>
  normal_dir: io
  abnormal_dir: nio
  normal_test_dir: eval/io
  task: classifcation
  root: /opt/<<path to images>>
model:
  name: padim
  backbone: resnet18
  pre_trained: true
project:
  seed: 42
  path: /opt/tests/anomaly_detection/results/padim/padim_test/run
  unique_dir: false
logging:
  logger: []
  log_graph: false
optimization:
  export_mode: null
trainer:
  enable_checkpointing: true
  default_root_dir: /opt/tests/anomaly_detection/results/padim/padim_test/run
```
My code is running in a Docker container. When I load the model with the given config, it will create the folder ```/opt/tests/anomaly_detection/results/padim/padim_test/run```. Inside this directory I have the following structure:
├── weights (empty directory)
├── images (empty directory)
├── config.yaml
├── config_original.yaml (copy of the yaml file I used for TorchInferencer)

Why are these folders created? How can I prevent this? I tried to set all paths in the config as None or let them empty but then I got errors. I would expect that I only need the config during inference for pre-processing, post-processing steps, thresholds etc.
