### ISSUE TITLE
[Bug]: Center Cropped gets weird visualize outputs

### ISSUE THREAD

**Issue by papago2355** [open-edge-platform/anomalib#1447]
### Describe the bug

I am currently using custom dataset to detect anomaly in belt.

### Dataset

Folder

### Model

PADiM

### Steps to reproduce the behavior

1. Use custom dataset
2. Resize image to 800x1600
3. Center cropped 720x620
4. Export by Openvino
5. load Openvino then predict
6. Use anomalib Visualizer

### OS information

OS information:
- OS: Windows
- Python version: 3.8.13
- Anomalib version: latests

### Expected behavior

Outputs masks are weird and not matched to the original input image.
Expected to be matched well or input would also get modified.

### Screenshots

![image](https://github.com/openvinotoolkit/anomalib/assets/68721273/79841500-5d6e-46c0-9cf8-db66d06b5966)

### Pip/GitHub

pip

### Configuration YAML

```yaml
dataset:
  name: belt_1026_0
  root: ./datasets
  format : folder
  task: classification
  normal_dir : belt_1026/ok_split/90
  abnormal_dir : belt_1026/ng_split/90
  mask : null
  normal_test_dir : null
  train_batch_size: 32
  eval_batch_size: 32
  extensions : null
  num_workers: 8
  image_size: [875,1600] # dimensions to which images are resized (mandatory)
  center_crop: [720,670] # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: same_as_test # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: 800
    stride: 800
    remove_border_count: 0
    use_random_tiling: false
    random_tile_count: 16

model:
  name: padim
  backbone: resnet18
  pre_trained: true
  layers:
    - layer1
    - layer2
    - layer3
  normalization_method: min_max # options: [none, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]

visualization:
  show_images: False # show images on the screen
  save_images: False # save images to the file system
  log_images: False # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: simple # options: ["full", "simple"]

project:
  seed: 42
  path: ./results/10_26_model_90

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: openvino # options: torch, onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
No logs
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
