### ISSUE TITLE
What happened to `image_size`?

### ISSUE THREAD

**Issue by thomaskleiven** [open-edge-platform/anomalib#2665]
In your latest [docs](https://anomalib.readthedocs.io/en/latest/markdown/guides/how_to/data/custom_data.html) you have an example where you pass `image_size` as an argument, but it seems like this is deprecated. How can we set the `image_size` in the latest version? 

```yaml
class_path: anomalib.data.Folder
init_args:
  name: "MVTecAD"
  root: "datasets/MVTecAD/transistor"
  normal_dir: "train/good"
  abnormal_dir: "test/bent_lead"
  normal_test_dir: "test/good"
  normal_split_ratio: 0
  extensions: [".png"]
  image_size: [256, 256]
  train_batch_size: 32
  eval_batch_size: 32
  num_workers: 8
  task: classification
  train_transform: null
  eval_transform: null
  test_split_mode: from_dir
  test_split_ratio: 0.2
  val_split_mode: same_as_test
  val_split_ratio: 0.5
  seed: null
```
