### ISSUE TITLE
[Bug]: The results obtained from OpenVINO and Torch Lightning are different.

### ISSUE THREAD

**Issue by huanghaiqiang** [open-edge-platform/anomalib#2744]
### Describe the bug

lightning

openvino

torch

### Dataset

N/A

### Model

PatchCore

### Steps to reproduce the behavior

![Image](https://github.com/user-attachments/assets/628869a9-5729-4019-91c5-204299a2a8b8)
![Image](https://github.com/user-attachments/assets/6af15cab-f2b3-4fcd-b34a-72199a66f176)
![Image](https://github.com/user-attachments/assets/64cacc5f-b0b1-43ed-b571-231f790ab15d)

### OS information

OS information:
- OS: [windows11]
- Python version: [3.11]
- Anomalib version: [2.0.0]
- PyTorch version: [2.5.1]
- CUDA/cuDNN version: [12.1]
- GPU models and configuration: [GeForce RTX 3070]
- Any other relevant information: [e.g. I'm using a custom dataset]

### Expected behavior

The reasoning results are consistent.

### Pip/GitHub

pip

### What version/branch did you use?

main

### Configuration YAML

```yaml
# anomalib==2.0.0
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger: null
  callbacks: null
  fast_dev_run: false
  max_epochs: null
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: null
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: null
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: null
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  model_registry: null
model:
  class_path: anomalib.models.Patchcore
  init_args:
    backbone: wide_resnet50_2
    layers:
    - layer2
    - layer3
    pre_trained: true
    coreset_sampling_ratio: 0.1
    num_neighbors: 9
    pre_processor: true
    post_processor: true
    evaluator: true
    visualizer: true
data: D:/Ai项目训练解决方案/差异检测/电路板裁切/DataSet/NG
return_predictions: null
ckpt_path: D:/Ai项目训练解决方案/差异检测/电路板裁切/TrainModel/best.ckpt
logging:
  log_graph: false
default_root_dir: results
```

### Logs

```shell
C:\CSN\AI\envs\a\python.exe C:\Users\Administrator\Desktop\Deep\main\anomalib-main\tools\inference\openvino_inference.py --weights D:/Ai项目训练解决方案/差异检测/电路板裁切/OutputModel\CPU.onnx --input D:/Ai项目训练解决方案/差异检测/电路板裁切/DataSet/NG/01_missing_hole_01_3.jpg --output results --visualization_mode full --show 
C:\CSN\AI\envs\a\lib\site-packages\openvino\runtime\__init__.py:10: DeprecationWarning: The `openvino.runtime` module is deprecated and will be removed in the 2026.0 release. Please replace `openvino.runtime` with `openvino`.
  warnings.warn(
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
