### ISSUE TITLE
[Bug]: Training a model without validation

### ISSUE THREAD

**Issue by hgaiser** [open-edge-platform/anomalib#977]
### Describe the bug

Most algorithms seem to assume that there is data available for automatically computing the threshold. In my case I only want to train an anomaly model, without validation or evaluation. This is as far as I can tell theoretically possible, however the way some post-epoch values are computed makes this impossible.

### Dataset

Folder

### Model

PatchCore

### Steps to reproduce the behavior

1. I used `main` branch ([commit ](https://github.com/openvinotoolkit/anomalib/commit/c92fb520d25911c5864ee251e4492348b7cc66c7)) but I would expect it to be the same on the latest released version.
2. I made some adjustments to [config.yaml](https://github.com/openvinotoolkit/anomalib/blob/main/src/anomalib/models/patchcore/config.yaml):
   1. Set `val_split_mode: none`.
   2. Set `export_mode: onnx`.

This will produce the following error:

```
RuntimeError: cdist only supports at least 2D tensors, X2 got: 1D
```

Which comes from [this](https://github.com/openvinotoolkit/anomalib/blob/c92fb520d25911c5864ee251e4492348b7cc66c7/src/anomalib/models/patchcore/torch_model.py#L156) line, because `self.memory_back` is an empty tensor at that point. This is because [this](https://github.com/openvinotoolkit/anomalib/blob/c92fb520d25911c5864ee251e4492348b7cc66c7/src/anomalib/models/patchcore/lightning_model.py#L86) never gets called, because there's no validation being performed.

Changing that function to `def on_train_epoch_end(self) -> None:` resolves the issue, and the process seems to complete successfully.

This change was introduced [here](https://github.com/openvinotoolkit/anomalib/pull/55/files#diff-42a6a9f15528f5c350642c244e07bbdfe169e0681b6f8cea227b7d4837e4a409R294-R300). Maybe @samet-akcay can shed some light on this?

### OS information

OS information:
- OS: Arch Linux
- Python version: 3.10.10
- Anomalib version: main branch
- PyTorch version: 2.0.0
- CUDA/cuDNN version: 12.1.0

### Expected behavior

I expect training and exporting to complete, regardless of validation being performed or not.

### Pip/GitHub

GitHub

### What version/branch did you use?

main

### Configuration YAML

```yaml
dataset:
  name: mvtec
  format: mvtec
  path: ./datasets/MVTec
  task: segmentation
  category: bottle
  train_batch_size: 32
  test_batch_size: 32
  num_workers: 8
  image_size: 256 # dimensions to which images are resized (mandatory)
  center_crop: 224 # dimensions to which images are center-cropped after resizing (optional)
  normalization: imagenet # data distribution to which the images will be normalized: [none, imagenet]
  transform_config:
    train: null
    eval: null
  test_split_mode: from_dir # options: [from_dir, synthetic]
  test_split_ratio: 0.2 # fraction of train images held out testing (usage depends on test_split_mode)
  val_split_mode: none # options: [same_as_test, from_test, synthetic]
  val_split_ratio: 0.5 # fraction of train/test images held out for validation (usage depends on val_split_mode)
  tiling:
    apply: false
    tile_size: null
    stride: null
    remove_border_count: 0
    use_random_tiling: False
    random_tile_count: 16

model:
  name: patchcore
  backbone: wide_resnet50_2
  pre_trained: true
  layers:
    - layer2
    - layer3
  coreset_sampling_ratio: 0.1
  num_neighbors: 9
  normalization_method: min_max # options: [null, min_max, cdf]

metrics:
  image:
    - F1Score
    - AUROC
  pixel:
    - F1Score
    - AUROC
  threshold:
    method: adaptive #options: [adaptive, manual]
    manual_image: null
    manual_pixel: null

visualization:
  show_images: False # show images on the screen
  save_images: True # save images to the file system
  log_images: True # log images to the available loggers (if any)
  image_save_path: null # path to which images will be saved
  mode: full # options: ["full", "simple"]

project:
  seed: 0
  path: ./results

logging:
  logger: [] # options: [comet, tensorboard, wandb, csv] or combinations.
  log_graph: false # Logs the model graph to respective logger.

optimization:
  export_mode: onnx # options: onnx, openvino

# PL Trainer Args. Don't add extra parameter here.
trainer:
  enable_checkpointing: true
  default_root_dir: null
  gradient_clip_val: 0
  gradient_clip_algorithm: norm
  num_nodes: 1
  devices: 1
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1 # Don't validate before extracting features.
  fast_dev_run: false
  accumulate_grad_batches: 1
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: 1.0
  limit_val_batches: 1.0
  limit_test_batches: 1.0
  limit_predict_batches: 1.0
  val_check_interval: 1.0 # Don't validate before extracting features.
  log_every_n_steps: 50
  accelerator: auto # <"cpu", "gpu", "tpu", "ipu", "hpu", "auto">
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  num_sanity_val_steps: 0
  profiler: null
  benchmark: false
  deterministic: false
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  plugins: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
```

### Logs

```shell
RuntimeError: cdist only supports at least 2D tensors, X2 got: 1D
```
```


### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
